version: "3.3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: example
        networks:
            - bridge_network

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - bridge_network

    application:
        build:
            context: ..
            dockerfile: Docker/debug.Dockerfile
        networks:
            - bridge_network
        depends_on:
            - db
        volumes:
            - ../data:/data

networks:
    bridge_network:
        driver: bridge